server:
  port: ":8081"

services:
  authn_url: "http://localhost:8082"
  authz_url: "http://localhost:8083"
  estate_url: "http://localhost:8084"
  dictionary_url: "http://localhost:8085"

auth:
  cache_ttl: "5m"
  session_secret: "change-this-in-production"

log:
  level: "info"

debug:
  routes: true

geocode:
  provider: "locationiq"
  # google:
  #   api_key: ""
  #   endpoint: "https://maps.googleapis.com/maps/api"
  # osm:
  #   endpoint: "https://nominatim.openstreetmap.org"
  #   email: ""
  locationiq:
    key: ""
    endpoint: "https://api.locationiq.com/v1"
